import './globals.css'
import type { Metadata } from 'next'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import { NavBar } from './NavBar'
import { Footer } from './Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons:{
    icon:'./favicon.ico'
  }
}

const Links = [
  {
    label :'Home',
    route : '/'
  },
  {
    label : 'Menu',
    route : '/menu'
  }
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar  />
        {children}
        <Footer/>
      </body>
    </html>
  )
}
